service: serverless-chrome-sls-plugin-test

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    DEBUG: "*"

plugins:
#  - serverless-plugin-typescript
  - serverless-plugin-chrome

custom:
  chrome:
    flags:
      - --window-size=1280,1696 # Letter size
      - --hide-scrollbars
      - --ignore-certificate-errors
    functions:
      - test
      - anotherTest

functions:
  test:
    handler: src/handler.default
  anotherTest:
    handler: src/anotherHandler.default
    package:
      # individually: true
  noChromeHere:
    handler: src/noChrome.default


  # typescript-test:
  #   handler: src/typescript-handler.default
